### ISSUE TITLE
(질문) rendezvous 띄우는 방법

### ISSUE THREAD

**Issue by disjukr** [langdev/rendezvous#9]
여기서 막혔는데,
![default](https://user-images.githubusercontent.com/690661/49748136-42e95400-fce8-11e8-9521-cbe85caf43d2.png)

윈도10 `rustc 1.32.0-nightly (0b9f19dff 2018-11-21)`에서 빌드는 잘 되었고 `dev.toml`은 다음과 같이 적었습니다:

```toml
[discord]
bot_token = "테스트용토큰내용"

[irc]
nickname = "testbot"
server = "irc.ozinger.org"
port = 6661
channels = ["테스트용채널이름"]
```

설정을 잘못 적어서 그런건가요? 아니면 윈도에서는 실행이 불가능한가요?
